### ISSUE TITLE
How to deal with a component that returns html?

### ISSUE THREAD

**Issue by jave** [whamtet/simpleui#35]
I have a component that calls an api that returns html. 

I would like to render that html, but when I use the hx-target method, the target component renders the html tags verbatim, rather than formated. If I reload the entire page, the html gets rendered though.

Since the documentation states that a component should return hiccup syntax, not html, I guess html might not be supported?

But how should I then deal with it? convert html to hiccup first?

TIA

**Comment by whamtet** [comment]
How about we make it so that components can return a string?  The html response will become that string.

**Comment by whamtet** [comment]
Any thoughts @jave ?

**Comment by jave** [comment]
Yes that would be a possibility, tnx!

**Comment by whamtet** [comment]
@jave it is supported.  As a safety measure you must set

    (simpleui.config/set-render-safe false)
